/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Wish = IDL.Record({
  'visitorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'wishText' : IDL.Text,
});
export const BirthdayProfile = IDL.Record({
  'giftBoxColor' : IDL.Text,
  'birthdayDate' : IDL.Text,
  'bowStyle' : IDL.Text,
  'senderName' : IDL.Text,
  'surpriseMessage' : IDL.Text,
  'ribbonColor' : IDL.Text,
  'backgroundTheme' : IDL.Text,
  'recipientName' : IDL.Text,
  'personalNote' : IDL.Text,
});

export const idlService = IDL.Service({
  'addWish' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'clearWishes' : IDL.Func([], [], []),
  'getAllWishes' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
  'getBirthdayProfile' : IDL.Func([], [BirthdayProfile], ['query']),
  'setBirthdayProfile' : IDL.Func([BirthdayProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Wish = IDL.Record({
    'visitorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'wishText' : IDL.Text,
  });
  const BirthdayProfile = IDL.Record({
    'giftBoxColor' : IDL.Text,
    'birthdayDate' : IDL.Text,
    'bowStyle' : IDL.Text,
    'senderName' : IDL.Text,
    'surpriseMessage' : IDL.Text,
    'ribbonColor' : IDL.Text,
    'backgroundTheme' : IDL.Text,
    'recipientName' : IDL.Text,
    'personalNote' : IDL.Text,
  });
  
  return IDL.Service({
    'addWish' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'clearWishes' : IDL.Func([], [], []),
    'getAllWishes' : IDL.Func([], [IDL.Vec(Wish)], ['query']),
    'getBirthdayProfile' : IDL.Func([], [BirthdayProfile], ['query']),
    'setBirthdayProfile' : IDL.Func([BirthdayProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };