/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BirthdayProfile {
  'giftBoxColor' : string,
  'birthdayDate' : string,
  'heroMessage' : string,
  'bowStyle' : string,
  'senderName' : string,
  'surpriseMessage' : string,
  'ribbonColor' : string,
  'backgroundTheme' : string,
  'recipientName' : string,
  'personalNote' : string,
}
export interface Wish {
  'visitorName' : string,
  'timestamp' : bigint,
  'wishText' : string,
}
export interface _SERVICE {
  'addWish' : ActorMethod<[string, string], undefined>,
  'clearWishes' : ActorMethod<[], undefined>,
  'getAllWishes' : ActorMethod<[], Array<Wish>>,
  'getBirthdayProfile' : ActorMethod<[], BirthdayProfile>,
  'setBirthdayProfile' : ActorMethod<[BirthdayProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];